
{% set rdir = "../.." %}
{% set data = load_setup_py_data(setup_file=''+rdir+'/setup.py', from_recipe_dir=True) %}
{% set version = time.strftime('%Y%m%d%H%M') %}

package:
  name: bitextor-nightly
  version: {{ version }}

source:
  - path: {{ rdir }}
    folder: bitextor
  - url: http://builds.archive.org/maven2/org/archive/heritrix/heritrix/3.4.0-SNAPSHOT/heritrix-3.4.0-SNAPSHOT-dist.zip
    folder: heritrix-3.4.0-SNAPSHOT

build:
  skip: True  # [not linux64]
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: "py{{ environ.get('CONDA_PY') }}_{{ environ.get('GIT_DESCRIBE_HASH') }}"
  preserve_egg_dir: True  # Some packages need this directory in order to work fine

requirements:
  build:
    - git
    - make
    - cmake
    - gcc_linux-64
    - gxx_linux-64
    - go-cgo 1.13.5 h77d97cf_0
  host:
    - boost
    - pip
    - setuptools
    - python {{ python }}
    - icu
    - unzip
    - libtool
    - wget
    - protobuf
    - libmagic
    - libzip
    - uchardet
    - gperftools
    - google-sparsehash
    - hunspell
  run:
    - pip
    - setuptools
    - python {{ python }}
    - boost
    - java-jdk 8
    - xz
    - time
    - poppler
    - poppler-data
    - curl
    - pigz
    - icu
    - wget
    - protobuf
    - libmagic
    - libzip
    - uchardet
    - gperftools
    - google-sparsehash
    - parallel
    - hunspell
    - hunspell-en

about:
  home: https://github.com/bitextor/bitextor/
  license: GPL3
  license_family: GPL3
  summary: Bitextor generates translation memories from multilingual websites
