.\" Manpage for bitextor-align-documents.
.\" Contact jferrandez@prompsit.com or mespla@dlsi.ua.es to correct errors or typos.
.TH bitextor-align-documents 1 "09 Sep 2013" "bitextor v4.0" "bitextor man pages"
.SH NAME
bitextor-align-documents \- This application is part of
.B bitextor
( the automatic bitext generator )

.SH SYNOPSIS
.B bitextor-align-documents
.RI [ OPTIONS ]
.br
.B bitextor-align-documents
.RI [ OPTIONS ]
.I RINDEX
.br
.B bitextor-align-documents
.RI [ OPTIONS ]
.I RINDEX
.I RINDEX

.SH DESCRIPTION
.B bitextor-align-documents
is a Python script that produces a list of aligned documents
from an
.I RINDEX
file which is produced by
.BR bitextor-distancefilter .
It is possible to provide only one
.I RINDEX
file, or to provide two (both obtained from the same website,
but one of them computed from
.B LANG1
to
.BR LANG2 ,
and the other 
computed from
.B LANG2
to
.BR LANG1 ).
In the first case, the content of the
.IR RINDEX ,
which can be read either from the standard input or from a
.IR FILE ,
the tool
only aligns every file in
.B LANG1
with the first candidate in
.BR LANG2 .
When two
.I RINDEX
files are provided, the candidate list is re-ranked by obtaining
the average score for every candidate pair in both directions.
It is worth noting that, if a candidate pair only exists in one
of the
.I RINDEX
files (i.e. in only one direction), it is removed from the list.
Finally, the best candidate pairs are used for document alignment.

.SH OPTIONS
.TP
.BI \-l " FILE"
path to the
.I LETTR 
file to be used as a list of documents to align.
.TP
.BI \-n " NUM"
Number of candidates to be taken into account when using two 
.I RINDEX
files. If no number is set for this option, all the available
candidates in the 
.I RINDEX
files are used.
.TP
.BI \-r " FILE"
path to the file where the
.I RINDEX 
resulting of the combination of the two
.I RINDEX 
files provided will be stored.
.TP

.SH SEE ALSO
bitextor-align-segments(1), bitextor(1), bitextor-downloadweb(1), bitextor-webdir2ett(1), bitextor-ett2lett(1),
bitextor-lett2idx(1), bitextor-idx2ridx(1), bitextor-lett2lettr(1),
bitextor-distancefilter(1), bitextor-cleantextalign(1), bitextor-buildTMX(1)

.SH BUGS
No known bugs.

.SH AUTHORS
.PD 0
.B Jorge Ferrández Tordera
.R <jferrandez@prompsit.com>
.P
.B Miquel Esplà-Gomis
.R <mespla@dlsi.ua.es>
