# nohup ~/.local/bin/snakemake --snakefile ../../Snakefile --cluster "sbatch --nice {cluster.oversubscribe} {cluster.gres}" --cluster-config ../cluster.json --cores 4222 -j 4222 -k --configfile  config.pt-en.yaml  &

bitextor: /home/s0565741/workspace/github/paracrawl/bitextor.malign

langstat: /home/hieu/transient/langstat/langstats.all.gz
langstatThreshold: 1000000
hostPath: /home/hieu/workspace/experiment/issues/paracrawl/prevHosts/hosts.lt.gz
linkedHosts: ["/home/hieu/permanent/hu-en",
             "/home/hieu/permanent/fr-en",
             "/home/hieu/permanent/de-en",
             "/home/hieu/permanent/it-en",
             "/home/hieu/permanent/es-en",
             "/home/hieu/permanent/pt-en",
             "/home/hieu/permanent/nl-en",
             "/home/hieu/permanent/cs-en",
             "/home/hieu/permanent/pl-en",
             "/home/hieu/permanent/da-en",
             "/home/hieu/permanent/el-en",
             "/home/hieu/permanent/ro-en",
             "/home/hieu/permanent/sv-en",
             "/home/hieu/permanent/fi-en",
             "/home/hieu/permanent/hr-en",
             "/home/hieu/permanent/bg-en",
             "/home/hieu/permanent/sk-en",
             "/home/hieu/permanent/et-en"]
linkedHostsAction: remove

langstatExcludeStrings: /home/hieu/permanent/software/bitextor/snakemake/langstat-exclude-strings
excludeHostsFile: /home/hieu/workspace/github/paracrawl/bitextor.malign/snakemake/exclude-hosts
temp: /raid0/tmp
permanentDir: /home/hieu/permanent/lt-en
transientDir: /home/hieu/transient/lt-en
lang1: lt
lang2: en
  #"dic: /home/hieu/permanent/software/bitextor-data/dics/en-fr.dic
hunalignThreshold: 0
maxlines: 5
crawlTimeLimit: 43200s
crawlPageLimit: 100000
tmx: true
nmt: false
smt: true
httrack: true

elrc: true
crawlerNumThreads: 2
crawlTld: false
  #"bicleanerThreshold: 0.7
#bicleaner: /home/hieu/transient/fr-en/bicleaner/en-fr.yaml
#bicleanerCorpusTrainingPrefix: ["/home/hieu/permanent/data/fr-en/train/europarl-v7.fr-en"]
documentAligner: SMT
alignerCmd: marek-smt
bleualign: true
docAlignThreshold: 0.1
bleuAlignThreshold: 0.2

marianDir: /home/hieu/permanent/software/marian-dev
subwordNmtDir: /home/hieu/permanent/software/subword-nmt
mosesDir: /home/hieu/permanent/software/mosesdecoder

marianArgs: [" --optimizer-delay 1 --mini-batch-fit --mini-batch 1000 --maxi-batch 1000",
                 " --overwrite --keep-best --valid-metrics perplexity",
                 " --valid-log valid.log --log train.log",
                 " --dropout-rnn 0.2 --dropout-src 0.2 --dropout-trg 0.2 ",
                 "--cost-type ce-mean-words --layer-normalization --exponential-smoothing --tied-embeddings",
                 "--valid-metrics bleu"
                ]
#marianModelFile: model.npz.decoder.yml
#marianModelFile: model.npz.best-perplexity.npz.decoder.yml
marianModelFile: model.npz.best-bleu.npz.decoder.yml

initCorpusTrainPrefix: ["/home/hieu/permanent/data/fr-en/train/europarl-v7.de-en",
                       ]
initCorpusDevPrefix: ["/home/hieu/permanent/data/fr-en/wmt07/dev/dev2006"]
initCorpusTestPrefix: ["/home/hieu/permanent/data/fr-en/wmt07/dev/dev2006",
                       "/home/hieu/permanent/data/fr-en/wmt07/dev/nc-dev2007",
                       "/home/hieu/permanent/data/fr-en/wmt07/devtest/devtest2006",
                       "/home/hieu/permanent/data/fr-en/wmt07/devtest/nc-devtest2007",
                       "/home/hieu/permanent/data/fr-en/wmt07/devtest/test2006.de"]

gpuId: 0
LANG1Tokenizer: /home/hieu/permanent/software/mosesdecoder/scripts/tokenizer/tokenizer.perl -b -l lt
LANG2Tokenizer: /home/hieu/permanent/software/mosesdecoder/scripts/tokenizer/tokenizer.perl -b -l en
LANG2Detokenizer: /home/hieu/permanent/software/mosesdecoder/scripts/tokenizer/detokenizer.perl -l en
LANG1SentenceSplitter: /home/hieu/permanent/software/mosesdecoder/scripts/ems/support/split-sentences.perl -l lt
LANG2SentenceSplitter: /home/hieu/permanent/software/mosesdecoder/scripts/ems/support/split-sentences.perl -l en

nmtVocabSize: 30000

mgiza: /home/hieu/permanent/software/mgiza
