.\" Manpage for bitextor-align-segments
.\" Contact jferrandez@prompsit.com or mespla@dlsi.ua.es to correct errors or typos.
.TH bitextor-train-document-alignment 1 "16 May 2016" "bitextor v5.0" "bitextor man pages"
.SH NAME
bitextor-train-document-alignment \- This application is part of
.B bitextor
( the automatic bitext generator )

.SH SYNOPSIS
.B bitextor-train-document-alignment
.RI [ OPTIONS ]
.BI \-w " WEIGHTS"
.BI \-m " MODEL"
.BI \-t " TRAININGFILE"
.BI \-d " DEVFILE"
.I [ RINDEX ]


.SH DESCRIPTION
.B bitextor-train-document-alignment
is a Python script that takes a
.IR TRAININGFILE
and a
.IR DEVFILE
containing a collection of training instances to build the regression
model to be used by the script
.IR bitextor-rank
for candidate ranking.

An example of the format expected for every instance in the develompent
and training files would be the following:

.B	66      161     0.179355659519  1.0     0.522540983607  0.0627118644068 0       0.169014084507  0.433333333333  0.0

As can be seen, this is a tab-sepparated list of fields for which the
first two fields correspond to the identifiers of the documents compared,
the last field corresponds to the value expected from regression (1.0 for
documents that are parallel, and 0.0 for documents that are not parallel),
and the remaining fields are the features to be used by the regressor.

This script uses the keras, a library that allows using neural networks,
to train the regressor. The resultim model is stored in the files
.IR MODEL
and
.IR WEIGHTS
defined by the user.

.SH OPTIONS
.TP
.BI \-t " TRAININGFILE"
Path to the training file
.TP
.BI \-d " DEVFILE"
Path to the development file
.TP
.BI \-w " WEIGHTS"
File containing the weights set for the neural netwokr, which is
obtained with the script
.B bitextor-train-document-alignment
.TP
.BI \-m " MODEL"
File containing the regression model to be used by the neural netwokr,
which is obtained with the script
.B bitextor-train-document-alignment
.TP
.BI \-b " NBEST"
Number of times that training is carried out with different initialisations;
in this way it is possible to keep only the best performing regressor among
those trained.

.SH SEE ALSO
bitextor-align-documents(1), bitextor(1), bitextor-downloadweb(1), bitextor-webdir2ett(1), bitextor-ett2lett(1),
bitextor-lett2idx(1), bitextor-idx2ridx(1), bitextor-lett2lettr(1),
bitextor-distancefilter(1), bitextor-cleantextalign(1), bitextor-buildTMX(1), hunalign(1)

.SH BUGS
No known bugs.

.SH AUTHORS
.PD 0
.B Jorge Ferrández Tordera
.R <jferrandez@prompsit.com>
.P
.B Miquel Esplà-Gomis
.R <mespla@dlsi.ua.es>
