#!/usr/bin/env python3

import argparse
import snakemake

oparser = argparse.ArgumentParser(description="lauch Bitextor")
                                               
oparser.add_argument("-c", "--config", dest="config", help="Bitextor configuration file", required=True)
oparser.add_argument("-j", "--jobs", dest="jobs", help="Number of provided cores", default=1)
oparser.add_argument("-k", "--keep-going", dest="keep_going", help="Go on with independent jobs if a job fails", action="store_true", default=False)
oparser.add_argument("--notemp", dest="notemp", help="Ignore temp() declarations, i.e. disable deletion of intermediate files", action="store_true", default=False)
oparser.add_argument("--dry-run", dest="dry_run", help="Do not execute anything and display what would be done", action="store_true", default=False)
oparser.add_argument("-q", "--quiet", dest="quiet", help="Do not print job information", action="store_true", default=False)
oparser.add_argument("--forceall", dest="forceall", help="Force rerun every job", action="store_true", default=False)

options = oparser.parse_args()

snakemake.snakemake(snakefile="workflow/Snakefile", configfiles=[options.config], cores=int(options.jobs), keepgoing=options.keep_going, notemp=options.notemp, dryrun=options.dry_run, quiet=options.quiet, forceall=options.forceall)
