
rule reduce:
   input:
    dynamic("e/{f}")
   output:
     'reduce'
   run:
     print("rule reduce", input)
     shell('touch reduce')

rule spawn:
   input:
    "d/{f}"
   output:
     'e/{f}'
   run:
     print("rule spawn", input)
     shell('touch {output}')


rule create_files:
  output: 
    dynamic("d/{f}")
  params:
    d = ["d/{} ".format(i) for i in range(10)]
  run:
    print("rule A", " ".join(params.d))
    shell('mkdir -p d && touch {}'.format(" ".join(params.d)))
    #shell('mkdir -p d && touch d/1')



