.\" Manpage for bitextor-distancefilter.
.\" Contact jferrandez@prompsit.com or mespla@dlsi.ua.es to correct errors or typos.
.TH bitextor-distancefilter 1 "09 Sep 2013" "bitextor v4.0" "bitextor man pages"
.SH NAME
bitextor-distancefilter \- This application is part of
.B bitextor
( the automatic bitext generator )

.SH SYNOPSIS
.B bitextor-distancefilter
file index

.SH DESCRIPTION
.B bitextor-distancefilter
is a Python program that performs a re-scoring of the candidates in a rindex file
by multiplying the current score by the fuzzy-match-score of the edit-distance of
the HTML structure of two candidates.
.PP
Receives two files: a .lettr file and .ridx file.
The output is a file with format .ridx but with the re-ranked candidates.

.SH DEPENDENCES
.B bitextor-distancefilter
depends on the
.B python-Levenshtein
Python library, which must be isntalled in advance. This library implements the Levenshtein edit distance between two strings
.TP

.SH SEE ALSO
bitextor-align-documents(1), bitextor-align-segments(1), bitextor(1),
bitextor-downloadweb(1), bitextor-webdir2ett(1), bitextor-ett2lett(1),
bitextor-lett2idx(1), bitextor-idx2ridx(1), bitextor-lett2lettr(1),
bitextor-aligner(1), bitextor-cleantextalign(1), bitextor-buildTMX(1)

.SH BUGS
No known bugs.

.SH AUTHORS
.PD 0
.B Jorge Ferrández Tordera
.R < jorgeferrandez@gmail.com >
.P
.B Miquel Esplà-Gomis
.R < mespla@dlsi.ua.es >
