.\" Manpage for bitextor-lett2lettr.
.\" Contact jferrandez@prompsit.com or mespla@dlsi.ua.es to correct errors or typos.
.TH bitextor-lett2lettr 1 "05 Jan 2011" "bitextor v4.0" "bitextor man pages"
.SH NAME
bitextor-lett2lettr \- This application is part of
.B bitextor
( the automatic bitext generator )

.SH SYNOPSIS
.B bitextor-lett2lettr
.RI [ FILE ]

.SH DESCRIPTION
.B bitextor-lett2lettr
is a Python script that takes a the output of
.B bitextor-ett2lett
as an imput, either from the standard imput or from a 
.IR FILE ,
and builds a representation (henceforth called \'raspa\') of the content
of each file in a string format. In this representation, the text in the
HTML is replaced by sequences of the symbol \'_\'. Actually, every text
piece in the file is replaced by
.B log2(len(TEXT))
'_' characters, where
.B len(TEXT)
is the number of words in the text. The text also keeps the name of the HTML
tags found in the document. This string is used by
.B bitextor-distancefilter
to compute the fuzzy-matching-score used to rank the parallel document candidates.
Once this representation is computed, it is concatenated to the sequence of
tab-separated fields received as an input.

.SH SEE ALSO
bitextor-align-documents(1), bitextor-align-segments(1), bitextor(1),
bitextor-downloadweb(1), bitextor-webdir2ett(1), bitextor-ett2lett(1),
bitextor-lett2idx(1), bitextor-idx2ridx(1), bitextor-distancefilter(1),
bitextor-aligner(1), bitextor-cleantextalign(1), bitextor-buildTMX(1)

.SH BUGS
No known bugs.

.SH AUTHORS
.PD 0
.B Jorge Ferrández Tordera
.R <jferrandez@prompsit.com>
.P
.B Miquel Esplà-Gomis
.R <mespla@dlsi.ua.es>
