.\" Manpage for bitextor-align-segments
.\" Contact jorgeferrandez@gmail.com to correct errors or typos.
.TH bitextor-align-segments 1 "09 Sep 2013" "bitextor v4.0" "bitextor man pages"
.SH NAME
bitextor-align-segments \- This application is part of
.B bitextor
( the automatic bitext generator )

.SH SYNOPSIS
.B bitextor-align-segments
--lang1 
.I LANG1
--lang2 
.I LANG2
.I FILE

.SH DESCRIPTION
.B bitextor-align-segments
is a Python script that produces a list of aligned segments from
a list of aligned documents in the rindex files. To call this tool
it is necessary to provide the language of the two file sets to be
aligned (
.I LANG1
and
.I LANG2
), which are used to choose the sentence-splitting rule set. The
list of aligned documents can be read from a
.I FILE
or from the standard input, and is provided from the script
.B bitextor-align-documents
.
This script produces two files with the concaenation of all the
files in
.I LANG1
and the other with the concatenation of all the files in
.I LANG2
. The files are concatenated following the same order, for both languages,
that the one provided by the document alignment. Hunalign (
.B http://mokk.bme.hu/resources/hunalign/
is then used to align the segments in the pair of files. It is worth
noting that the concatenated files are sepparated by the mark
.B <p>
, which ensures that the pairs of segments will be obtained from the
same pair of documents. This concatenation is performed to ensure a
reasonable ammount of text to be aligned, in order to build a better
dictionary for
.B hunalign.

.SH SEE ALSO
bitextor-align-documents(1), bitextor(1), bitextor-downloadweb(1), bitextor-webdir2ett(1), bitextor-ett2lett(1),
bitextor-lett2idx(1), bitextor-idx2ridx(1), bitextor-lett2lettr(1),
bitextor-distancefilter(1), bitextor-cleantextalign(1)

.SH BUGS
No known bugs.

.SH AUTHORS
.PD 0
.B Jorge Ferrández Tordera
.R < jorgeferrandez@gmail.com >

.B Miquel Esplà-Gomis
.R < mespla@dlsi.ua.es >
