.\" Manpage for bitextor-downloadweb.
.\" Contact jorgeferrandez@gmail.com to correct errors or typos.
.TH bitextor-downloadweb 1 "05 Jan 2011" "bitextor v4.0" "bitextor man pages"
.SH NAME
bitextor-downloadweb \- This application is part of
.B bitextor
( the automatic bitext generator )

.SH SYNOPSIS
.B bitextor-downloadweb
url [dirname]

.SH DESCRIPTION
.B bitextor-downloadweb
is shell program for download an entire website.

.SH SEE ALSO
bitextor(1), bitextor-webdir2ett(1), bitextor-ett2lett(1), bitextor-lett2idx(1),
bitextor-idx2ridx(1), bitextor-lett2lettr(1), bitextor-distancefilter(1),
bitextor-aligner(1), bitextor-cleantextalign(1), httrack(1)

.SH BUGS
No known bugs.

.SH AUTHOR
Jorge Ferrández Tordera (jorgeferrandez@gmail.com)
