.\" Manpage for bitextor-ett2lett.
.\" Contact jorgeferrandez@gmail.com to correct errors or typos.
.TH bitextor-ett2lett 1 "05 Jan 2011" "bitextor v4.0" "bitextor man pages"
.SH NAME
bitextor-ett2lett \- This application is part of
.B bitextor
( the automatic bitext generator )

.SH SYNOPSIS
.B bitextor-ett2lett
file

.SH DESCRIPTION
.B bitextor-ett2lett
is python script to detect language of the files. The script reads the output
of bitextor-webdir2ett and produces a new tab-sepparated output containing the same
fields that the one produced by bitextor-webdir2ett, but concatenating the detected
language for every file. The language identification is performed by using the python
library LangID.py.
.PP
Receives a file with format .ett and the output is a file with format .lett

.SH SEE ALSO
bitextor(1), bitextor-downloadweb(1), bitextor-webdir2ett(1), bitextor-lett2idx(1),
bitextor-idx2ridx(1), bitextor-lett2lettr(1), bitextor-distancefilter(1),
bitextor-aligner(1), bitextor-cleantextalign(1)

.SH BUGS
No known bugs.

.SH AUTHOR
Jorge Ferrández Tordera (jorgeferrandez@gmail.com)
Miquel Esplà-Gomis (mespla@dlsi.ua.es)
