.\" Manpage for bitextor-lett2idx.
.\" Contact jferrandez@prompsit.com or mespla@dlsi.ua.es to correct errors or typos.
.TH bitextor-lett2idx 1 "09 Sep 2013" "bitextor v4.0" "bitextor man pages"
.SH NAME
bitextor-lett2idx \- This application is part of
.B bitextor
( the automatic bitext generator )

.SH SYNOPSIS
.B bitextor-lett2idx
file

.SH DESCRIPTION
.B bitextor-lett2idx
is a python script that obtains an index indicating, for every word in a
crawled website, which files contain, at least, one occurrence of the word.
The script uses as an imput the output of the script bitextor-ett2lett
A different list of words are built for every language detected in the website.
The output of this script is a tab-sepparated file containing, in teh first
field, a language code, in the second, a word, and in the third, a list of
document indexes, sepparated by a collon, in which the word appears.
To reduce the size of the output, the file indexes is presented as an incremental
shifting. In this way, the first file in the list is the one with the lower index.
Then, the next identifiers are only the increment to add to the former index in order
to obtain the real file code.
.PP
Receives a file with format .lett and the output is a file with format .idx

.SH SEE ALSO
bitextor-align-documents(1), bitextor-align-segments(1), bitextor(1),
bitextor-downloadweb(1), bitextor-webdir2ett(1), bitextor-ett2lett(1),
bitextor-idx2ridx(1), bitextor-lett2lettr(1), bitextor-distancefilter(1),
bitextor-aligner(1), bitextor-cleantextalign(1), bitextor-buildTMX(1)

.SH BUGS
No known bugs.

.SH AUTHORS
.PD 0
.B Jorge Ferrández Tordera
.R <jferrandez@prompsit.com>
.P
.B Miquel Esplà-Gomis
.R <mespla@dlsi.ua.es>
