.\" Manpage for bitextor-webdir2ett.
.\" Contact jferrandez@prompsit.com or mespla@dlsi.ua.es to correct errors or typos.
.TH bitextor-webdir2ett 1 "09 Sep 2013" "bitextor v4.0" "bitextor man pages"
.SH NAME
bitextor-webdir2ett \- This application is part of
.B bitextor
( the automatic bitext generator from multilingual websites )

.SH SYNOPSIS
.B bitextor-webdir2ett
webdir

.SH DESCRIPTION
.B bitextor-webdir2ett
is a bash/python script to process the files downloaded from a web site.
This script extracts the encoding, the mimetype, the URI and the content
of each file encoded in base64. This script uses the library BoilerPipe
to remove menus and unuseful parts of the HTML files. Then, Apache-Tika
is used to fix errors in the HTML structure and obtain a version of the
file in XHTML. The encoding is also normalised to UTF-8.
.PP
Receives the path to a crawled web directory and the output is a file
tab-sepparated file containing the name of the original encoding, the
mimetype, and the base64-encoded text.

.SH DEPENDENCES
.B bitextor-webdir2ett
depends on the Python library
.B python-boilerpipe
which provide a Python interface to use the Java package
boilerpipe for cleaning those parts of an HTML file that contain useless
information, such as menus, adds, etc. This library must be installed
in advance to use this scipt.

.SH SEE ALSO
bitextor-align-documents(1), bitextor-align-segments(1), bitextor(1),
bitextor-downloadweb(1), bitextor-ett2lett(1), bitextor-lett2idx(1),
bitextor-idx2ridx(1), bitextor-lett2lettr(1), bitextor-distancefilter(1),
bitextor-aligner(1), bitextor-cleantextalign(1), bitextor-buildTMX(1)

.SH BUGS
No known bugs.

.SH AUTHORS
.PD 0
.B Jorge Ferrández Tordera
.R < jorgeferrandez@gmail.com >
.P
.B Miquel Esplà-Gomis
.R < mespla@dlsi.ua.es >
