.\" Manpage for bitextor-distancefilter.
.\" Contact jferrandez@prompsit.com or mespla@dlsi.ua.es to correct errors or typos.
.TH bitextor-distancefilter 1 "09 Sep 2013" "bitextor v4.0" "bitextor man pages"
.SH NAME
bitextor-distancefilter \- This application is part of
.B bitextor
( the automatic bitext generator )

.SH SYNOPSIS
.B bitextor-distancefilter
.RI [ OPTIONS ]
.RI [ FILE ]

.SH DESCRIPTION
.BR bitextor-distancefilter ,
which computes, for every document in
.IR LANG1 ,
the set of the 10-best candidate documents to be parallel in
.I LANG2
by using a metric computed on the bag of words of every document.
The re-scoring is performed by multiplying the score of every candidate
by the fuzzy-matching-score between the document and the candidates.
The fuzzy-matching-score is based on the Levenshtein's edit distance
between the documents, which is computed by means of the library
.BR python-Levenshtein ,
which must be installed in advance.

.SH OPTIONS
.TP
.BI \-l " FILE"
path to the
.I LETTR 
file containing the information about the processed documents in the website.

.SH DEPENDENCES
.TP
.B python-Levenshtein
Python library that implements the Levenshtein edit distance between two strings

.SH SEE ALSO
bitextor-align-documents(1), bitextor-align-segments(1), bitextor(1),
bitextor-downloadweb(1), bitextor-webdir2ett(1), bitextor-ett2lett(1),
bitextor-lett2idx(1), bitextor-idx2ridx(1), bitextor-lett2lettr(1),
bitextor-aligner(1), bitextor-cleantextalign(1), bitextor-buildTMX(1)

.SH BUGS
No known bugs.

.SH AUTHORS
.PD 0
.B Jorge Ferrández Tordera
.R <jferrandez@prompsit.com>
.P
.B Miquel Esplà-Gomis
.R <mespla@dlsi.ua.es>
