.\" Manpage for bitextor-cleantextalign.
.\" Contact jorgeferrandez@gmail.com to correct errors or typos.
.TH bitextor-cleantextalign 1 "05 Jan 2011" "bitextor v4.0" "bitextor man pages"
.SH NAME
bitextor-cleantextalign \- This application is part of
.B bitextor
( the automatic bitext generator )

.SH SYNOPSIS
.B bitextor-cleantextalign
align [-m max_lines] [-q min_quality]

.SH DESCRIPTION
.B bitextor-cleantextalign
is bash script that that filters unreliable segment pairs produced by
.B bitextor-align-segments. The file recieves
.PP
Receives a file with format .align and the output is a file with all bitexts found.

.SH OPTIONS
-m max_lines      clean texts (clean lines by default) and specify maximum number
of lines out of alignment (5 by default)
.PP
-q min_quality    minimum quality required for each line (0 by default)

.SH SEE ALSO
bitextor-align-documents(1), bitextor-align-segments(1), bitextor(1),
bitextor-downloadweb(1), bitextor-webdir2ett(1), bitextor-ett2lett(1),
bitextor-lett2idx(1), bitextor-idx2ridx(1), bitextor-lett2lettr(1),
bitextor-distancefilter(1), bitextor-aligner(1)

.SH BUGS
No known bugs.

.SH AUTHORS
.PD 0
.B Jorge Ferrández Tordera
.R < jorgeferrandez@gmail.com >

.B Miquel Esplà-Gomis
.R < mespla@dlsi.ua.es >
