.\" Manpage for bitextor-idx2ridx.
.\" Contact jferrandez@prompsit.com or mespla@dlsi.ua.es to correct errors or typos.
.TH bitextor-idx2ridx 1 "09 Sep 2013" "bitextor v4.0" "bitextor man pages"
.SH NAME
bitextor-idx2ridx \- This application is part of
.B bitextor
( the automatic bitext generator )

.SH SYNOPSIS
.B bitextor-idx2ridx
[-d dictionary] [idx] lang1 lang2

.SH DESCRIPTION
.B bitextor-idx2ridx
is a python script that takes a .idx file produced by bitextor-lett2idx
(weather from a file or from the standard input) and produces a list of
the 10 most promising files in lang2 to be aligned for every file in 
lang1. The output format is a tab-sepparated file; for each line in this
file, the first field corresponds to the code of the file in lang1 for which
the candidates will be presented. The next 10 fields are a list of tuples
separated by a colon, in which the left field is the code of a candidate in
lang2, and the right field is the confidence score asigned to the candidate.

The candidates detection is peformed by: a) getting the list of words for every
file, b) using the dictionary for translating the words in every file in lang2
into lang1, and c) computing a matching score between the words in every pair
of documents. A default dictionary is distributed with bitextor for English,
Spanish, Catalan, Croatian, and Basque. However, it is possible to provide
a custom dictionary by using the option -d to determine the path to the dictionry
field. A dictionary must follow the following format:
- it must be a tab-sepparated file;
- the first line must contain the language code for the words in every language included in the dictionary;
- the rest of the lines must contain translations of a word into each of the languages specified in the first line;
.PP
Receives a .idx file and the code of two languages.
The output is a file with format .ridx

.SH SEE ALSO
bitextor-align-documents(1), bitextor-align-segments(1), bitextor(1),
bitextor-downloadweb(1), bitextor-webdir2ett(1), bitextor-ett2lett(1),
bitextor-lett2idx(1), bitextor-lett2lettr(1), bitextor-distancefilter(1),
bitextor-aligner(1), bitextor-cleantextalign(1), bitextor-buildTMX(1)

.SH BUGS
No known bugs.

.SH AUTHORS
.PD 0
.B Jorge Ferrández Tordera
.R <jferrandez@prompsit.com>
.P
.B Miquel Esplà-Gomis
.R <mespla@dlsi.ua.es>
