
#include "gtest/gtest.h"
#include "../src/ngram.h"

#include <vector>


namespace {

    TEST(ngram, test_NGramCounter) {

      std::vector<std::string> tokens_lorem1 = {"Ipsum", "numquam", "labore", "ut", "est", "aliquam", "dolore", "modi",
                                                "tempora", "magnam", "magnam", "ipsum", "consectetur", "dolorem",
                                                "quiquia",
                                                "quisquam", "non", "ut", "porro", "dolor", "dolor", "quiquia",
                                                "voluptatem",
                                                "quaerat", "porro", "velit", "eius", "modi", "ipsum", "velit", "sed",
                                                "etincidunt", "amet", "est", "non", "modi", "consectetur", "dolor",
                                                "aliquam", "labore", "eius", "eius", "dolorem", "magnam", "eius",
                                                "dolore",
                                                "adipisci", "aliquam", "dolorem", "dolorem", "voluptatem", "adipisci",
                                                "etincidunt", "quaerat", "numquam", "modi", "adipisci", "quaerat",
                                                "non",
                                                "ipsum", "quaerat.", "Magnam", "quiquia", "sed", "amet", "quisquam",
                                                "amet",
                                                "dolor", "neque", "tempora", "non", "magnam", "quaerat", "modi",
                                                "voluptatem", "tempora", "adipisci", "dolorem", "magnam", "sed", "amet",
                                                "neque", "numquam", "aliquam", "est", "eius", "quisquam", "porro",
                                                "ipsum",
                                                "sit", "magnam", "est", "modi", "modi", "quisquam", "sed", "numquam.",
                                                "Neque", "dolore", "numquam", "modi", "ut", "ipsum", "porro",
                                                "etincidunt",
                                                "quisquam", "sit", "adipisci", "modi", "sed", "numquam", "amet",
                                                "numquam",
                                                "dolorem", "magnam", "quaerat", "labore", "dolore", "quiquia", "dolor",
                                                "aliquam", "tempora", "sit", "quaerat", "quiquia", "numquam", "quaerat",
                                                "tempora", "etincidunt", "quisquam", "voluptatem", "ipsum", "est",
                                                "ipsum",
                                                "modi", "amet", "ipsum", "voluptatem", "neque", "non", "amet", "magnam",
                                                "labore", "sed", "porro", "dolor", "ut", "dolor", "eius", "sed", "non",
                                                "dolore", "amet", "ut", "adipisci", "consectetur", "eius", "etincidunt",
                                                "voluptatem.", "Sit", "consectetur", "labore", "non", "eius", "labore",
                                                "labore", "eius", "porro", "velit", "numquam", "amet", "consectetur",
                                                "etincidunt", "dolore", "amet", "quisquam", "eius", "velit", "tempora",
                                                "sed", "adipisci", "amet", "voluptatem", "sit", "non", "sed", "magnam",
                                                "labore", "numquam", "labore", "adipisci", "labore", "eius", "dolor",
                                                "est",
                                                "velit", "porro", "ipsum", "ut", "non", "amet", "quaerat", "tempora.",
                                                "Voluptatem", "quiquia", "eius", "dolorem", "amet", "voluptatem",
                                                "consectetur", "ipsum", "velit", "magnam", "numquam", "adipisci", "ut",
                                                "voluptatem", "labore", "ut", "porro", "dolorem", "sed", "tempora",
                                                "porro",
                                                "porro", "non", "magnam", "est", "sed", "velit", "amet", "aliquam",
                                                "consectetur", "aliquam", "modi", "aliquam", "etincidunt", "amet", "ut",
                                                "numquam", "velit", "sed", "non", "ipsum", "eius", "amet", "neque",
                                                "etincidunt", "dolorem", "eius", "sit", "numquam", "porro", "labore",
                                                "quaerat", "dolore", "dolore.", "Tempora", "quisquam", "velit", "sed",
                                                "etincidunt", "porro", "consectetur", "velit", "sit", "dolorem",
                                                "etincidunt", "etincidunt", "dolorem", "dolor", "sit", "magnam",
                                                "tempora",
                                                "ut", "magnam", "dolore", "eius", "voluptatem", "amet", "non", "dolor",
                                                "modi", "sit", "labore", "quaerat", "non", "sit", "etincidunt",
                                                "aliquam",
                                                "etincidunt", "adipisci", "quaerat", "velit.", "Modi", "dolorem", "est",
                                                "magnam", "porro", "ipsum", "quaerat", "voluptatem", "aliquam", "velit",
                                                "dolore", "voluptatem", "velit", "aliquam", "voluptatem", "dolorem",
                                                "neque", "ut", "neque", "etincidunt", "magnam", "tempora", "adipisci",
                                                "ipsum", "modi", "ipsum", "quaerat", "ipsum", "ut", "ipsum", "labore",
                                                "est", "adipisci", "labore", "porro", "non", "amet", "porro.",
                                                "Consectetur", "eius", "sit", "adipisci", "voluptatem", "dolore",
                                                "labore",
                                                "ut", "quisquam", "dolorem", "numquam", "non", "ut", "eius", "non",
                                                "aliquam", "dolor", "sed", "magnam", "quisquam", "sed", "quaerat",
                                                "dolor",
                                                "aliquam", "dolore", "ut", "amet", "magnam", "porro", "est", "est",
                                                "ut",
                                                "neque", "dolore", "non.", "Est", "dolor", "magnam", "ipsum", "tempora",
                                                "voluptatem", "ut", "dolor", "ut", "neque", "etincidunt", "porro",
                                                "consectetur", "ut", "quiquia", "numquam", "labore", "porro", "labore",
                                                "est", "aliquam", "voluptatem", "modi", "amet", "est", "modi",
                                                "aliquam",
                                                "amet", "ut", "adipisci", "amet", "aliquam", "etincidunt", "amet",
                                                "quiquia", "modi", "dolor", "quisquam", "porro", "consectetur", "porro",
                                                "dolore", "numquam", "dolor", "est", "ipsum", "sed", "magnam", "eius",
                                                "velit", "neque", "modi", "dolorem", "dolor", "quaerat.", "Velit",
                                                "magnam",
                                                "voluptatem", "dolore", "sed", "magnam", "voluptatem", "sit", "dolore",
                                                "dolorem", "neque", "quisquam", "voluptatem", "ut", "dolorem",
                                                "etincidunt",
                                                "etincidunt", "numquam", "magnam", "consectetur", "tempora", "tempora",
                                                "ipsum", "sit", "sed", "quisquam", "ut", "modi", "etincidunt",
                                                "consectetur", "neque", "neque", "labore.", "Ut", "quaerat", "quaerat",
                                                "voluptatem", "est", "sed", "magnam", "ut", "modi", "sed", "amet",
                                                "labore",
                                                "eius", "dolore", "dolorem", "tempora", "adipisci", "dolor", "quaerat",
                                                "dolorem", "magnam", "aliquam", "quaerat", "quisquam", "numquam",
                                                "tempora",
                                                "quaerat", "eius", "quaerat", "voluptatem", "labore", "magnam", "dolor",
                                                "neque", "dolor", "magnam", "etincidunt", "non", "sit", "etincidunt",
                                                "quiquia", "dolor", "labore", "eius", "eius", "tempora", "dolore",
                                                "neque",
                                                "etincidunt", "consectetur", "modi.", "Dolor", "porro", "numquam",
                                                "dolore",
                                                "ut", "tempora", "adipisci", "ut", "etincidunt", "quisquam", "tempora",
                                                "neque", "consectetur", "eius", "est", "adipisci", "adipisci", "porro",
                                                "adipisci", "dolore", "etincidunt", "quiquia", "quisquam",
                                                "consectetur",
                                                "etincidunt", "tempora", "quisquam", "etincidunt", "amet", "sed",
                                                "quiquia",
                                                "quisquam", "dolor", "adipisci", "sit", "amet", "ut", "porro", "eius",
                                                "dolor", "modi", "labore", "numquam", "amet", "neque.", "Dolore",
                                                "dolore",
                                                "adipisci", "amet", "velit", "amet", "magnam", "dolore", "tempora",
                                                "porro",
                                                "dolor", "etincidunt", "adipisci", "ipsum", "est", "quaerat", "est",
                                                "velit", "sit", "velit", "numquam", "est", "voluptatem", "sit",
                                                "tempora",
                                                "dolor", "dolor", "voluptatem", "consectetur.", "Quiquia", "quiquia",
                                                "quisquam", "quiquia", "adipisci", "dolorem", "voluptatem",
                                                "etincidunt",
                                                "dolore", "amet", "labore", "sit", "modi", "quisquam", "ipsum",
                                                "tempora",
                                                "quaerat", "eius", "labore", "voluptatem", "porro", "neque",
                                                "etincidunt",
                                                "eius", "labore", "ut", "quiquia", "quaerat", "velit", "modi", "porro",
                                                "numquam", "porro", "etincidunt", "consectetur", "modi", "est", "sed",
                                                "consectetur", "sit", "etincidunt", "adipisci", "sed", "adipisci",
                                                "voluptatem", "etincidunt", "est", "etincidunt", "quiquia",
                                                "etincidunt",
                                                "modi", "sit", "consectetur", "labore", "adipisci", "ipsum", "sed",
                                                "velit",
                                                "quisquam", "magnam", "sed", "quisquam", "sit", "dolore", "magnam",
                                                "porro",
                                                "dolore", "porro", "labore", "amet.", "Est", "dolor", "labore", "est",
                                                "non", "dolorem", "sed", "quaerat", "modi", "eius", "sit", "est",
                                                "neque",
                                                "est", "sit", "aliquam", "sed", "ipsum", "quaerat", "sit", "eius",
                                                "est",
                                                "magnam", "magnam", "velit", "dolore", "amet", "eius", "velit", "ipsum",
                                                "non", "aliquam", "dolore", "ut", "porro", "modi", "numquam", "tempora",
                                                "quiquia", "dolorem", "tempora", "neque", "magnam", "tempora",
                                                "dolorem",
                                                "magnam", "eius", "tempora", "est", "magnam", "amet", "consectetur",
                                                "dolor", "porro.", "Voluptatem", "labore", "consectetur", "dolor",
                                                "dolore",
                                                "ut", "quaerat", "aliquam", "ut", "quisquam", "sed", "adipisci",
                                                "dolore",
                                                "velit", "non", "dolorem", "tempora", "magnam", "magnam", "neque",
                                                "ipsum",
                                                "aliquam", "dolore", "consectetur", "sed", "amet", "numquam", "amet",
                                                "ut",
                                                "magnam", "adipisci", "consectetur", "ipsum", "numquam", "modi", "est",
                                                "ut", "sed", "numquam", "non", "ipsum", "numquam", "ipsum", "velit",
                                                "numquam", "etincidunt", "amet.", "Velit", "ut", "modi", "dolorem",
                                                "voluptatem", "adipisci", "non", "adipisci", "dolor", "dolore",
                                                "adipisci",
                                                "velit", "quisquam", "magnam", "adipisci", "etincidunt", "est", "ut",
                                                "amet", "ut", "ipsum", "adipisci", "dolor", "quiquia", "aliquam",
                                                "neque",
                                                "dolore", "quaerat", "porro", "etincidunt", "ipsum", "sit", "labore",
                                                "labore", "magnam", "dolorem", "adipisci", "quaerat", "dolore",
                                                "tempora",
                                                "sit", "labore", "est", "aliquam", "tempora", "tempora", "modi",
                                                "ipsum",
                                                "magnam.", "Non", "quiquia", "consectetur", "dolor", "dolore", "neque",
                                                "tempora", "ut", "labore", "adipisci", "eius", "magnam", "aliquam",
                                                "velit",
                                                "dolor", "eius", "sit", "est", "magnam", "quaerat", "sit", "magnam",
                                                "non",
                                                "ipsum", "eius", "quaerat", "ipsum", "velit", "etincidunt", "neque",
                                                "etincidunt", "sit", "aliquam.", "Modi", "sed", "dolorem", "velit",
                                                "sit",
                                                "numquam", "tempora", "modi", "porro", "numquam", "tempora", "tempora",
                                                "consectetur", "dolore", "dolor", "est", "etincidunt", "eius", "est",
                                                "sed",
                                                "ut", "etincidunt", "non", "velit", "labore", "adipisci", "etincidunt",
                                                "aliquam", "ipsum", "adipisci", "eius", "non", "est", "est", "sit",
                                                "non",
                                                "sed", "adipisci", "dolore", "modi", "etincidunt", "non", "porro",
                                                "quaerat", "non", "tempora", "etincidunt", "numquam", "neque",
                                                "dolorem",
                                                "quiquia", "amet", "est", "numquam", "est", "quaerat", "dolorem",
                                                "quiquia",
                                                "porro", "ut", "consectetur", "non", "velit", "dolor", "amet.", "Neque",
                                                "quiquia", "sit", "quiquia", "sed", "magnam", "amet", "tempora",
                                                "voluptatem", "tempora", "adipisci", "dolor", "labore", "ipsum", "ut",
                                                "dolorem", "porro", "velit", "sed", "etincidunt", "tempora", "tempora",
                                                "quisquam", "velit", "numquam", "sed", "modi", "non", "consectetur",
                                                "quisquam", "quiquia", "voluptatem", "amet", "ipsum", "dolore", "sit.",
                                                "Numquam", "magnam", "velit", "sit", "quiquia", "modi", "quisquam",
                                                "quisquam", "numquam", "ut", "labore", "dolor", "adipisci", "dolore",
                                                "porro", "sit", "est", "etincidunt", "dolor", "adipisci", "labore",
                                                "tempora", "quisquam", "ut", "etincidunt", "sed", "consectetur.",
                                                "Quisquam", "tempora", "quaerat", "non", "magnam", "labore", "dolorem",
                                                "ipsum", "porro", "voluptatem", "voluptatem", "labore", "labore",
                                                "labore",
                                                "est", "quisquam", "labore", "numquam", "dolor", "labore", "quaerat",
                                                "aliquam", "numquam", "adipisci", "aliquam", "neque", "tempora",
                                                "labore",
                                                "non", "numquam", "numquam", "etincidunt", "quaerat", "sed", "neque",
                                                "etincidunt", "tempora", "consectetur", "numquam", "quisquam", "sit",
                                                "sed",
                                                "est", "magnam", "neque", "adipisci", "ipsum", "modi", "modi",
                                                "quiquia",
                                                "ut", "consectetur", "velit", "ut", "dolorem", "modi", "neque",
                                                "consectetur", "numquam", "neque", "sed", "labore", "tempora",
                                                "numquam",
                                                "sit", "amet", "quiquia", "modi", "consectetur", "sed.", "Est", "sit",
                                                "etincidunt", "labore", "adipisci", "quaerat", "sed", "non", "porro",
                                                "amet", "adipisci", "consectetur", "neque", "magnam", "ut", "sit",
                                                "sed",
                                                "modi", "numquam", "consectetur", "dolore", "ut", "dolor", "velit",
                                                "aliquam", "quiquia", "dolorem", "ut", "amet", "quaerat", "velit",
                                                "quisquam", "modi", "ipsum", "sed", "dolor", "neque", "labore", "amet",
                                                "dolorem", "modi", "dolore", "quaerat", "quiquia", "est", "etincidunt.",
                                                "Sed", "non", "ipsum", "sed", "dolor", "porro", "dolorem", "modi",
                                                "est",
                                                "velit", "quisquam", "ut", "quiquia", "tempora", "tempora", "velit",
                                                "ipsum", "aliquam", "velit", "porro", "labore", "velit", "modi",
                                                "porro",
                                                "dolorem", "numquam", "ut", "dolor", "tempora", "non."};
      ngram::NGramCounter ngc_lorem1(1);
      ngc_lorem1.process(tokens_lorem1);
      ASSERT_EQ(ngc_lorem1.count_tokens(), 63);
      ASSERT_EQ(ngc_lorem1.get(ngram::NGramContainer("etincidunt")), 50);
      ASSERT_EQ(ngc_lorem1.get(ngram::NGramContainer("est")), 41);
      ASSERT_EQ(ngc_lorem1.get(ngram::NGramContainer("Modi")), 2);

      std::vector<std::string> tokens_lorem2 = {"Dolorem", "voluptatem", "sed", "voluptatem", "amet", "sed", "sed",
                                                "porro",
                                                "dolorem", "quiquia", "dolore", "non", "quiquia", "quaerat", "dolorem",
                                                "eius", "modi", "tempora", "etincidunt.", "Velit", "ut", "voluptatem",
                                                "velit", "est", "ut", "est", "adipisci", "neque", "sed", "quaerat",
                                                "porro",
                                                "quaerat", "numquam", "etincidunt.", "Sit", "adipisci", "dolore",
                                                "adipisci", "eius", "quaerat", "velit", "neque", "ut", "eius", "labore",
                                                "adipisci", "ipsum", "consectetur", "labore", "consectetur", "non.",
                                                "Labore", "sed", "quisquam", "adipisci", "porro", "porro", "dolorem",
                                                "numquam", "labore", "aliquam", "sed", "sed", "ipsum", "ipsum",
                                                "voluptatem", "dolorem", "dolore", "modi", "neque", "ipsum", "amet",
                                                "quiquia", "est.", "Eius", "porro", "dolorem", "amet", "sit", "aliquam",
                                                "dolor", "tempora", "velit", "amet", "dolore", "ipsum", "voluptatem",
                                                "porro", "sed", "adipisci.", "Magnam", "voluptatem", "velit", "sed",
                                                "quisquam", "etincidunt", "sit", "voluptatem", "magnam", "non",
                                                "quiquia",
                                                "etincidunt", "est", "quaerat", "amet", "non", "non", "consectetur.",
                                                "Ut",
                                                "velit", "est", "est", "numquam", "magnam", "eius", "quisquam",
                                                "consectetur", "sed", "neque", "voluptatem", "ipsum", "dolore", "sit",
                                                "dolorem", "aliquam", "modi", "dolor", "amet", "eius", "quiquia",
                                                "dolor",
                                                "labore", "dolorem", "est", "quisquam", "ipsum", "eius", "velit",
                                                "quiquia",
                                                "amet", "labore.", "Etincidunt", "quiquia", "voluptatem", "dolorem",
                                                "labore", "neque", "velit", "sed", "magnam", "dolorem", "adipisci",
                                                "velit",
                                                "modi", "ut", "non", "non", "aliquam", "eius", "modi", "sit", "amet",
                                                "dolore", "ipsum", "velit", "eius", "numquam", "amet", "eius", "magnam",
                                                "voluptatem", "consectetur", "ut.", "Ut", "aliquam", "ut", "aliquam",
                                                "ipsum", "sed", "consectetur", "amet", "velit", "eius", "ipsum", "modi",
                                                "quisquam", "labore", "labore", "etincidunt", "aliquam", "quisquam",
                                                "voluptatem", "non", "eius", "velit", "modi", "non", "labore", "porro",
                                                "neque", "ipsum", "numquam", "eius.", "Sed", "dolore", "etincidunt",
                                                "dolore", "non", "numquam", "modi", "sed", "modi", "aliquam", "dolorem",
                                                "tempora", "etincidunt", "eius", "quiquia", "aliquam", "adipisci",
                                                "voluptatem", "voluptatem", "numquam", "eius.", "Modi", "dolore",
                                                "dolore",
                                                "adipisci", "aliquam", "porro", "sit", "dolor", "labore", "velit",
                                                "modi",
                                                "dolor", "voluptatem", "neque", "non.", "Velit", "eius", "sit", "non",
                                                "amet", "quaerat", "sit", "etincidunt", "consectetur", "etincidunt",
                                                "dolore", "magnam", "labore", "quisquam", "ipsum", "modi", "labore",
                                                "voluptatem", "quiquia", "non", "voluptatem", "porro", "amet", "neque",
                                                "labore", "dolore", "velit", "numquam", "labore", "modi.", "Sed",
                                                "eius",
                                                "sit", "adipisci", "consectetur", "dolor", "modi", "consectetur",
                                                "tempora",
                                                "numquam", "consectetur", "modi", "dolorem", "amet", "sit", "non",
                                                "dolor",
                                                "etincidunt", "neque", "sit", "magnam", "sit.", "Dolor", "est", "amet",
                                                "sit", "tempora", "sit", "sed", "porro", "amet", "etincidunt", "ut",
                                                "ut",
                                                "aliquam", "velit", "porro", "tempora", "quiquia", "est", "est",
                                                "ipsum",
                                                "sed", "dolor", "quaerat", "neque", "sit", "tempora", "dolor", "amet",
                                                "sit", "non", "aliquam", "voluptatem.", "Aliquam", "consectetur",
                                                "quaerat",
                                                "dolor", "labore", "modi", "adipisci", "quaerat", "modi", "velit",
                                                "etincidunt", "dolor", "etincidunt", "dolore", "amet", "etincidunt",
                                                "quiquia", "quiquia", "porro", "etincidunt", "modi", "ipsum",
                                                "voluptatem",
                                                "eius", "quaerat", "quaerat", "dolorem", "sit", "dolore", "neque",
                                                "tempora.", "Quiquia", "est", "amet", "quisquam", "est", "non", "sit",
                                                "amet", "magnam", "magnam", "velit", "dolorem", "amet", "porro", "ut",
                                                "non", "sit", "amet", "neque", "porro", "adipisci", "adipisci",
                                                "adipisci",
                                                "quisquam", "porro", "labore", "eius", "neque", "dolor", "eius",
                                                "quaerat",
                                                "magnam.", "Dolore", "amet", "sit", "non", "dolore", "voluptatem",
                                                "quisquam", "labore", "dolorem", "quisquam", "sit", "magnam", "est",
                                                "ut",
                                                "est", "est", "non", "quiquia", "dolor", "dolorem", "ut", "amet",
                                                "adipisci.", "Porro", "dolorem", "est", "neque", "voluptatem",
                                                "quaerat",
                                                "magnam", "quiquia", "est", "aliquam", "eius", "modi", "aliquam",
                                                "etincidunt", "aliquam.", "Modi", "porro", "ipsum", "sed", "adipisci",
                                                "magnam", "dolore", "adipisci", "ipsum", "dolore", "consectetur",
                                                "numquam",
                                                "sit", "porro", "dolore", "ut", "aliquam", "non", "tempora", "magnam",
                                                "eius", "amet", "quaerat", "adipisci", "numquam", "aliquam", "porro",
                                                "sed.", "Quiquia", "tempora", "amet", "voluptatem", "neque", "eius",
                                                "quiquia", "quisquam", "magnam", "tempora", "quaerat", "amet", "modi",
                                                "dolorem", "labore", "non", "magnam", "labore", "modi", "etincidunt",
                                                "quaerat.", "Non", "est", "amet", "porro", "dolor", "sit", "aliquam",
                                                "dolor", "ipsum", "velit", "voluptatem", "dolorem", "adipisci", "sed",
                                                "non", "ut", "adipisci", "modi", "ut", "dolore", "numquam", "porro.",
                                                "Sit",
                                                "ut", "consectetur", "amet", "neque", "dolore", "eius", "dolor", "est",
                                                "aliquam", "ut", "numquam", "labore", "dolorem", "quiquia", "neque",
                                                "ipsum", "sit", "voluptatem", "sed", "neque", "labore", "non",
                                                "aliquam",
                                                "velit", "magnam", "non", "est", "ipsum", "quiquia", "aliquam",
                                                "adipisci",
                                                "etincidunt", "quaerat."};
      ngram::NGramCounter ngc_lorem2(2);
      ngc_lorem2.process(tokens_lorem2);
      ASSERT_EQ(ngc_lorem2.count_tokens(), 465);
      ASSERT_EQ(ngc_lorem2.get(ngram::NGramContainer("voluptatem", "velit")), 2);
      ASSERT_EQ(ngc_lorem2.get(ngram::NGramContainer("aliquam")), 20);
      ASSERT_EQ(ngc_lorem2.get(ngram::NGramContainer("amet", "sit")), 5);

      std::vector<std::string> tokens_lorem3 = {"Dolore", "labore", "amet", "dolorem", "porro", "numquam", "ipsum",
                                                "eius",
                                                "tempora", "magnam", "neque", "neque", "ut", "aliquam", "magnam",
                                                "dolor",
                                                "dolor", "voluptatem", "velit", "tempora", "consectetur", "est", "amet",
                                                "ipsum", "sit", "tempora", "modi", "dolore", "quaerat", "modi",
                                                "adipisci",
                                                "quisquam", "porro", "amet", "dolore", "adipisci", "labore", "dolor",
                                                "velit", "neque", "etincidunt", "tempora", "magnam", "dolore",
                                                "voluptatem",
                                                "dolore", "eius", "quaerat", "tempora", "amet", "sit", "voluptatem",
                                                "quiquia", "ipsum", "numquam", "voluptatem", "quisquam.", "Sed",
                                                "quisquam",
                                                "sed", "non", "modi", "magnam", "dolore", "quisquam", "sit", "aliquam",
                                                "adipisci", "voluptatem", "labore", "dolor", "ut", "est", "quisquam",
                                                "quisquam", "sed", "amet", "ut", "etincidunt", "quisquam", "quisquam",
                                                "amet", "sit", "quisquam", "porro", "numquam", "dolorem", "ut",
                                                "quiquia",
                                                "aliquam", "neque", "consectetur", "dolorem", "dolor", "eius",
                                                "quiquia",
                                                "ut", "dolor", "etincidunt", "porro", "sed", "eius", "modi", "dolorem",
                                                "non.", "Est", "quisquam", "magnam", "aliquam", "est", "neque", "dolor",
                                                "velit", "sed", "amet", "porro", "neque", "dolore", "voluptatem",
                                                "quisquam", "porro", "ut", "dolor", "velit", "consectetur", "porro",
                                                "dolorem", "dolorem", "consectetur", "voluptatem", "voluptatem",
                                                "consectetur", "dolore", "amet", "magnam", "sed", "porro", "labore",
                                                "adipisci", "modi", "eius", "voluptatem", "consectetur", "quisquam",
                                                "sit",
                                                "eius", "sed", "est.", "Tempora", "neque", "voluptatem", "voluptatem",
                                                "labore", "velit", "modi", "amet", "est", "ipsum", "velit", "magnam",
                                                "non",
                                                "ut", "voluptatem", "modi", "modi", "sed", "quaerat", "quaerat", "modi",
                                                "dolorem", "numquam", "ipsum", "sit", "ut", "velit", "aliquam",
                                                "adipisci",
                                                "numquam", "sed", "sed", "adipisci", "labore", "numquam", "ipsum",
                                                "aliquam", "dolorem", "sed", "magnam", "ut", "quisquam.", "Tempora",
                                                "ut",
                                                "quiquia", "neque", "sit", "ipsum", "sed", "ut", "quisquam",
                                                "voluptatem",
                                                "sit", "adipisci", "porro", "sed", "consectetur", "non", "modi", "modi",
                                                "dolor", "labore", "tempora", "consectetur", "sit", "adipisci", "sed",
                                                "modi", "adipisci", "etincidunt", "amet", "porro", "voluptatem", "sit",
                                                "quaerat", "sed", "etincidunt", "quaerat", "modi", "quiquia",
                                                "adipisci",
                                                "dolore", "adipisci", "quisquam", "neque", "sed", "quaerat", "ipsum",
                                                "aliquam", "non", "tempora", "etincidunt", "adipisci", "amet.",
                                                "Quaerat",
                                                "labore", "numquam", "magnam", "sit", "quaerat", "adipisci", "modi",
                                                "est",
                                                "quaerat", "consectetur", "non", "etincidunt", "est", "sed", "ipsum",
                                                "sit",
                                                "dolor", "ipsum", "modi", "etincidunt", "aliquam", "tempora", "quaerat",
                                                "adipisci", "adipisci", "dolor", "sit", "est", "velit", "magnam",
                                                "amet",
                                                "etincidunt", "dolore", "ut", "labore", "modi", "eius", "labore",
                                                "quisquam", "labore", "labore", "etincidunt", "adipisci", "tempora",
                                                "adipisci", "dolore", "eius", "non", "tempora", "est", "numquam",
                                                "etincidunt", "quaerat", "amet", "quaerat", "quiquia", "amet",
                                                "labore.",
                                                "Non", "dolorem", "magnam", "sed", "sed", "dolor", "etincidunt", "sed",
                                                "ut", "neque", "est", "quisquam", "dolor", "dolorem", "numquam",
                                                "ipsum",
                                                "neque", "non", "dolore", "numquam", "ipsum", "voluptatem",
                                                "etincidunt",
                                                "dolore", "quisquam", "magnam", "aliquam", "sit", "etincidunt",
                                                "quisquam",
                                                "velit", "dolor", "ut", "magnam", "voluptatem", "amet", "dolore",
                                                "numquam",
                                                "amet", "quiquia", "labore", "etincidunt", "sed", "magnam", "magnam.",
                                                "Quaerat", "aliquam", "porro", "dolor", "neque", "neque", "voluptatem",
                                                "porro", "dolor", "tempora", "quiquia", "sed", "amet", "velit", "est",
                                                "sit", "magnam", "quaerat", "neque", "magnam", "voluptatem", "quiquia",
                                                "neque", "etincidunt", "porro", "adipisci", "ipsum", "quiquia",
                                                "quiquia",
                                                "quiquia", "voluptatem", "numquam", "sed", "magnam", "quaerat",
                                                "aliquam",
                                                "dolor", "voluptatem", "eius", "ipsum", "tempora.", "Consectetur",
                                                "voluptatem", "amet", "labore", "numquam", "numquam", "ipsum", "non",
                                                "consectetur", "sit", "ut", "quisquam", "voluptatem", "numquam", "eius",
                                                "ut", "dolore", "quisquam", "porro", "dolorem", "magnam", "magnam",
                                                "adipisci", "amet", "non", "non", "quisquam", "ipsum", "est", "velit",
                                                "ipsum", "ipsum", "eius", "quisquam", "ut", "tempora", "ut", "numquam",
                                                "numquam", "amet", "neque", "quiquia", "modi", "consectetur", "tempora",
                                                "quiquia", "sit", "sed.", "Dolorem", "dolor", "sed", "eius", "quisquam",
                                                "ut", "dolor", "quisquam", "numquam", "labore", "voluptatem", "labore",
                                                "quiquia", "quiquia", "non", "porro", "labore", "eius", "non", "ut",
                                                "aliquam", "etincidunt", "dolore", "quiquia", "amet", "consectetur",
                                                "tempora", "magnam", "est", "tempora", "dolor", "eius", "dolor",
                                                "consectetur", "quiquia", "porro", "quisquam", "quaerat", "modi", "sed",
                                                "velit", "tempora", "porro", "dolor", "voluptatem", "amet", "numquam",
                                                "ut",
                                                "modi", "dolor.", "Magnam", "ut", "magnam", "amet", "consectetur",
                                                "neque",
                                                "eius", "modi", "eius", "etincidunt", "quaerat", "sed", "dolor",
                                                "neque",
                                                "etincidunt", "voluptatem", "adipisci", "modi", "tempora", "adipisci",
                                                "dolor", "etincidunt", "est", "aliquam", "modi", "amet", "modi",
                                                "labore",
                                                "dolore", "est", "voluptatem", "voluptatem", "quisquam", "dolor",
                                                "voluptatem", "magnam", "porro", "tempora", "dolor", "tempora",
                                                "dolorem",
                                                "amet", "est", "porro", "dolor", "quiquia", "etincidunt", "etincidunt",
                                                "dolor", "neque.", "Magnam", "voluptatem", "voluptatem", "quisquam",
                                                "neque", "sit", "quaerat", "sed", "dolore", "velit", "adipisci",
                                                "quaerat",
                                                "adipisci", "velit", "dolor", "est", "adipisci", "sed", "sed",
                                                "voluptatem",
                                                "eius", "neque", "velit", "etincidunt", "etincidunt", "ipsum", "porro",
                                                "amet", "aliquam", "dolore", "sed", "tempora", "amet", "non", "ut",
                                                "dolor",
                                                "quisquam", "etincidunt", "velit", "numquam", "labore", "velit",
                                                "neque",
                                                "etincidunt.", "Numquam", "adipisci", "sit", "ipsum", "est", "labore",
                                                "non", "neque", "tempora", "dolor", "est", "consectetur", "magnam",
                                                "est",
                                                "quaerat", "dolor", "dolorem", "numquam", "adipisci", "eius", "neque",
                                                "porro", "magnam", "magnam", "amet", "modi", "non", "sit", "etincidunt",
                                                "magnam", "voluptatem", "adipisci", "dolorem", "adipisci", "ut",
                                                "velit",
                                                "dolor", "adipisci", "etincidunt", "est", "dolor", "numquam", "labore",
                                                "aliquam.", "Etincidunt", "amet", "sed", "magnam", "amet", "dolore",
                                                "tempora", "adipisci", "dolorem", "ipsum", "dolor", "modi", "neque",
                                                "velit", "non", "ut", "sit", "neque", "consectetur", "velit", "porro",
                                                "est", "eius", "consectetur", "magnam", "voluptatem", "tempora", "amet",
                                                "modi", "aliquam", "etincidunt", "aliquam", "adipisci", "est", "sit",
                                                "adipisci", "tempora", "consectetur", "velit", "aliquam", "quiquia",
                                                "amet",
                                                "consectetur", "neque", "consectetur", "dolor", "sit", "labore.", "Ut",
                                                "numquam", "eius", "voluptatem", "labore", "modi", "amet", "tempora",
                                                "labore", "neque", "aliquam", "voluptatem", "ut", "eius", "sed",
                                                "labore",
                                                "magnam", "adipisci", "ut", "neque", "modi", "eius", "quisquam",
                                                "voluptatem", "tempora", "amet", "dolore", "quaerat", "sit", "velit",
                                                "magnam", "velit", "magnam", "ipsum", "quiquia", "velit", "modi",
                                                "neque",
                                                "neque", "sed", "aliquam", "velit", "tempora.", "Labore", "aliquam",
                                                "dolorem", "numquam", "labore", "voluptatem", "consectetur", "aliquam",
                                                "aliquam", "adipisci", "ipsum", "consectetur", "neque", "sit",
                                                "voluptatem",
                                                "est", "tempora", "ut", "voluptatem", "quiquia", "labore", "numquam",
                                                "consectetur", "voluptatem", "magnam", "est", "porro", "est", "neque",
                                                "amet", "dolorem", "dolor", "quaerat", "dolore", "tempora", "aliquam",
                                                "neque", "porro", "neque", "quisquam.", "Eius", "velit", "sed",
                                                "adipisci",
                                                "dolorem", "ut", "modi", "modi", "sed", "dolorem", "sit", "non",
                                                "dolore",
                                                "consectetur", "est", "sit", "velit", "numquam", "eius", "aliquam",
                                                "numquam", "modi", "numquam", "ipsum", "quisquam", "est", "dolore",
                                                "modi",
                                                "etincidunt", "magnam", "eius", "dolorem", "eius", "adipisci", "magnam",
                                                "quisquam", "ipsum", "etincidunt", "voluptatem", "non", "aliquam",
                                                "dolore",
                                                "neque.", "Magnam", "eius", "quaerat", "adipisci", "dolore", "sit",
                                                "numquam", "velit", "tempora", "amet", "amet", "eius", "quaerat",
                                                "dolore",
                                                "tempora", "quiquia", "dolore", "dolore", "consectetur", "tempora",
                                                "etincidunt", "dolore", "velit", "porro", "neque", "neque", "eius",
                                                "sit",
                                                "neque", "neque", "velit", "magnam", "dolor", "dolorem", "adipisci",
                                                "adipisci", "quiquia", "dolorem", "eius", "quisquam", "est", "ut",
                                                "quiquia", "sit", "dolore", "amet", "aliquam", "porro", "amet",
                                                "voluptatem", "non", "ut", "labore", "velit", "sit.", "Sit", "velit",
                                                "est",
                                                "velit", "dolorem", "magnam", "non", "magnam", "aliquam", "eius",
                                                "dolor",
                                                "quaerat", "etincidunt", "ipsum", "eius", "eius", "consectetur",
                                                "quaerat",
                                                "neque", "etincidunt", "etincidunt", "non", "quaerat", "adipisci",
                                                "dolor",
                                                "dolore", "sed", "ipsum", "magnam", "neque", "dolor", "est", "magnam",
                                                "sed", "ipsum", "consectetur", "modi", "etincidunt", "dolore", "dolore",
                                                "dolorem", "consectetur", "consectetur", "numquam", "voluptatem",
                                                "consectetur", "porro", "numquam", "etincidunt.", "Consectetur",
                                                "quiquia",
                                                "aliquam", "quaerat", "etincidunt", "dolor", "est", "tempora", "magnam",
                                                "eius", "adipisci", "dolore", "sit", "labore", "est", "aliquam",
                                                "labore",
                                                "quaerat", "adipisci", "dolor", "magnam", "eius", "tempora", "labore",
                                                "consectetur", "modi", "quisquam", "non", "non", "dolore", "aliquam",
                                                "magnam", "neque", "quiquia", "amet", "amet", "amet", "dolore", "dolor",
                                                "sed", "dolor", "adipisci", "etincidunt", "porro.", "Adipisci",
                                                "tempora",
                                                "modi", "ut", "adipisci", "quisquam", "ipsum", "quisquam", "non",
                                                "velit",
                                                "neque", "tempora", "neque", "eius", "dolore", "porro", "ut", "quaerat",
                                                "quaerat", "neque", "quaerat", "porro", "amet", "eius", "dolore",
                                                "quiquia",
                                                "amet", "quisquam", "quiquia", "velit", "etincidunt", "dolore",
                                                "labore",
                                                "modi", "modi", "sit", "voluptatem", "tempora", "est", "aliquam", "ut",
                                                "ut", "est", "dolor", "velit", "etincidunt", "quisquam", "aliquam",
                                                "ipsum",
                                                "sed", "neque", "porro", "modi", "porro", "eius", "dolore", "porro",
                                                "neque", "neque.", "Magnam", "est", "ipsum", "aliquam", "porro",
                                                "dolore",
                                                "ipsum", "consectetur", "adipisci", "voluptatem", "amet", "non",
                                                "numquam",
                                                "amet", "magnam", "labore", "etincidunt", "sit", "consectetur", "velit",
                                                "quisquam", "labore", "labore", "neque", "dolor", "consectetur",
                                                "quaerat",
                                                "porro", "ipsum", "voluptatem", "modi", "ut", "sed", "etincidunt",
                                                "eius",
                                                "porro", "quiquia", "voluptatem", "dolorem", "eius", "etincidunt",
                                                "est.",
                                                "Aliquam", "magnam", "dolor", "eius", "ipsum", "quiquia", "quisquam",
                                                "dolore", "dolorem", "amet", "eius", "eius", "ut", "dolorem", "neque",
                                                "quisquam", "neque", "numquam", "quisquam", "numquam", "sed", "velit",
                                                "ut",
                                                "sed", "voluptatem", "dolorem", "ut", "numquam", "dolor", "modi",
                                                "adipisci", "numquam", "consectetur", "dolorem", "sit", "neque",
                                                "quisquam",
                                                "etincidunt", "adipisci", "est", "quiquia", "quisquam", "quaerat",
                                                "quiquia", "dolorem", "amet", "voluptatem", "quiquia", "numquam",
                                                "eius",
                                                "labore", "numquam", "consectetur", "tempora", "dolore", "ut", "sed",
                                                "dolore.", "Ut", "dolorem", "amet", "ipsum", "adipisci", "sit",
                                                "voluptatem", "amet", "dolore", "sed", "dolor", "quiquia", "neque",
                                                "dolore", "modi", "quiquia", "ipsum", "dolorem", "numquam", "labore",
                                                "neque", "non", "aliquam", "adipisci", "tempora", "labore", "porro",
                                                "est",
                                                "consectetur", "dolorem", "sit", "numquam", "est", "sit", "consectetur",
                                                "dolorem", "adipisci", "ut", "voluptatem", "modi", "dolorem.", "Est",
                                                "numquam", "non", "numquam", "porro", "adipisci", "voluptatem", "sit",
                                                "consectetur", "quiquia", "sit", "ut", "eius", "aliquam", "est",
                                                "tempora",
                                                "voluptatem", "magnam", "amet", "etincidunt", "sed", "non",
                                                "etincidunt",
                                                "consectetur", "etincidunt", "quaerat", "dolore", "amet", "sit", "amet",
                                                "voluptatem", "eius", "dolore", "ut", "adipisci", "tempora", "eius",
                                                "quaerat", "sit", "etincidunt", "ipsum", "numquam.", "Porro", "quaerat",
                                                "consectetur", "quiquia", "etincidunt", "dolorem", "dolorem", "quiquia",
                                                "sit", "dolore", "dolore", "dolore", "dolore", "neque", "non", "amet",
                                                "quiquia", "numquam", "sed", "numquam", "modi", "porro", "dolore",
                                                "sed",
                                                "ipsum", "etincidunt", "labore", "amet", "dolor", "velit", "ut",
                                                "tempora",
                                                "neque", "numquam", "porro", "eius", "etincidunt", "adipisci", "ut",
                                                "dolore", "ut", "labore", "sed", "sed", "dolor", "dolore", "numquam",
                                                "eius", "labore", "magnam", "sed", "labore", "voluptatem", "sit.",
                                                "Tempora", "dolorem", "ut", "sed", "etincidunt", "etincidunt", "ipsum",
                                                "voluptatem", "ipsum", "etincidunt", "quiquia", "modi", "porro",
                                                "consectetur", "tempora", "dolor", "ipsum", "non", "neque", "velit",
                                                "adipisci", "quaerat", "numquam", "non", "velit", "quiquia", "est",
                                                "dolorem", "porro", "dolorem", "magnam", "dolore", "sed", "voluptatem",
                                                "sit", "dolore", "voluptatem", "porro", "dolorem", "quisquam", "ipsum",
                                                "ipsum", "aliquam", "dolor", "numquam", "sed", "neque", "velit",
                                                "magnam",
                                                "quisquam", "ipsum", "sit", "amet", "quiquia", "ipsum", "est", "neque.",
                                                "Aliquam", "quisquam", "dolore", "consectetur", "ipsum", "etincidunt",
                                                "dolor", "velit", "quaerat", "quiquia", "modi", "adipisci", "magnam",
                                                "ipsum", "modi", "quaerat", "amet", "consectetur", "dolore", "tempora",
                                                "etincidunt", "consectetur", "quisquam", "labore", "porro", "neque",
                                                "magnam", "velit", "dolore", "quaerat", "eius", "consectetur",
                                                "voluptatem",
                                                "non", "est", "neque", "modi", "voluptatem", "consectetur", "aliquam.",
                                                "Voluptatem", "dolorem", "non", "numquam", "porro", "ipsum", "dolor",
                                                "numquam", "est", "aliquam", "sit", "voluptatem", "ut", "dolore", "sed",
                                                "modi", "ipsum", "voluptatem", "quaerat", "ut", "aliquam", "eius",
                                                "eius",
                                                "ipsum", "porro", "porro", "voluptatem", "etincidunt", "ipsum", "velit",
                                                "amet", "modi", "modi", "eius", "dolor", "adipisci", "consectetur",
                                                "non",
                                                "ut", "adipisci", "consectetur", "amet", "eius.", "Modi", "magnam",
                                                "quiquia", "consectetur", "sit", "non", "neque", "quaerat", "amet",
                                                "est",
                                                "magnam", "tempora", "eius", "est", "labore", "amet", "sed", "dolore",
                                                "modi", "quiquia", "ipsum", "non", "eius", "amet", "ut", "labore",
                                                "modi",
                                                "voluptatem", "labore", "modi", "est", "voluptatem", "quaerat",
                                                "quiquia",
                                                "velit", "voluptatem", "ipsum", "dolore", "adipisci", "labore", "neque",
                                                "quisquam", "ipsum", "velit", "etincidunt", "quisquam", "quiquia",
                                                "est",
                                                "porro", "ut", "sit", "neque.", "Porro", "adipisci", "ipsum",
                                                "consectetur",
                                                "magnam", "velit", "neque", "est", "amet", "dolorem", "porro",
                                                "quiquia",
                                                "non", "est", "neque", "labore", "eius", "porro", "quaerat", "sit",
                                                "porro",
                                                "tempora", "numquam", "quaerat", "non", "numquam", "numquam", "labore",
                                                "magnam", "modi", "dolore", "eius", "non", "etincidunt", "adipisci",
                                                "ut",
                                                "tempora", "est", "etincidunt", "quisquam", "ut", "sit", "aliquam",
                                                "neque",
                                                "dolorem", "consectetur", "dolor", "sed", "ut", "non", "magnam",
                                                "neque",
                                                "ut", "amet."};
      ngram::NGramCounter ngc_lorem3(3);
      ngc_lorem3.process(tokens_lorem3);
      ASSERT_EQ(ngc_lorem3.count_tokens(), 2197);
      ASSERT_EQ(ngc_lorem3.get(ngram::NGramContainer("velit", "magnam")), 6);
      ASSERT_EQ(ngc_lorem3.get(ngram::NGramContainer("neque")), 64);
      ASSERT_EQ(ngc_lorem3.get(ngram::NGramContainer("ut", "quisquam", "voluptatem")), 2);

      std::vector<std::string> tokens_lorem4 = {"Magnam", "amet", "ipsum", "modi", "modi", "numquam", "tempora",
                                                "quiquia",
                                                "ut", "dolor", "eius", "eius", "porro.", "Consectetur", "dolor",
                                                "neque",
                                                "quiquia", "quisquam", "tempora", "aliquam", "dolore", "aliquam",
                                                "aliquam",
                                                "magnam", "neque.", "Consectetur", "velit", "magnam", "quisquam",
                                                "quiquia",
                                                "neque", "non", "dolore", "quisquam", "dolorem", "magnam.", "Porro",
                                                "est",
                                                "consectetur", "neque", "quaerat", "adipisci", "neque", "velit",
                                                "consectetur", "quiquia", "eius", "neque", "ut", "dolorem", "adipisci.",
                                                "Dolor", "eius", "labore", "quiquia", "quisquam", "magnam", "quaerat",
                                                "ipsum", "quaerat", "consectetur", "labore", "magnam.", "Neque",
                                                "quiquia",
                                                "ipsum", "quaerat", "porro", "quiquia", "aliquam", "ipsum", "amet",
                                                "ut",
                                                "quisquam", "quisquam", "ut", "dolorem", "etincidunt", "etincidunt",
                                                "tempora", "quiquia", "est", "numquam.", "Amet", "labore", "labore",
                                                "ipsum", "dolorem", "quaerat", "velit", "sit", "dolor", "dolore",
                                                "ipsum",
                                                "ipsum", "numquam.", "Numquam", "amet", "ut", "velit", "dolor",
                                                "tempora",
                                                "non", "quisquam", "non", "modi", "non.", "Sit", "ut", "quisquam",
                                                "dolore",
                                                "labore", "dolor", "ut", "dolor", "quisquam", "voluptatem", "dolorem",
                                                "amet", "neque", "amet.", "Sit", "labore", "ut", "dolorem", "porro",
                                                "dolore", "neque", "amet", "ipsum", "voluptatem", "sit", "dolor",
                                                "adipisci", "ut", "dolore.", "Neque", "neque", "amet", "neque", "sed",
                                                "non", "etincidunt", "velit", "labore", "non", "voluptatem", "magnam",
                                                "consectetur", "tempora", "quaerat", "ut.", "Quisquam", "est",
                                                "quaerat",
                                                "aliquam", "modi", "quiquia", "labore", "numquam", "numquam",
                                                "adipisci",
                                                "consectetur", "eius", "neque", "aliquam", "neque", "quiquia",
                                                "quaerat",
                                                "porro.", "Consectetur", "aliquam", "eius", "ipsum", "quisquam",
                                                "neque",
                                                "dolor", "voluptatem", "dolore", "ut", "sit", "amet", "est", "quaerat",
                                                "quisquam", "numquam", "sed", "est", "quisquam.", "Etincidunt", "neque",
                                                "quaerat", "dolor", "modi", "voluptatem", "sit", "consectetur", "modi",
                                                "est", "amet", "numquam", "dolorem", "non", "quiquia.", "Quisquam",
                                                "sed",
                                                "modi", "etincidunt", "etincidunt", "neque", "adipisci", "quaerat",
                                                "etincidunt", "modi", "dolorem", "sit", "non", "dolore", "velit", "non",
                                                "etincidunt", "consectetur", "eius.", "Quiquia", "sed", "aliquam",
                                                "labore",
                                                "ut", "dolorem", "dolorem", "neque", "voluptatem", "etincidunt", "est",
                                                "quiquia", "eius", "voluptatem", "ut", "neque.", "Ipsum", "eius",
                                                "quiquia",
                                                "adipisci", "porro", "quisquam", "magnam", "modi", "quiquia", "tempora",
                                                "sed", "sit", "quisquam", "dolor", "numquam", "quaerat", "dolore.",
                                                "Ipsum",
                                                "ipsum", "porro", "etincidunt", "quisquam", "eius", "quaerat",
                                                "etincidunt",
                                                "numquam", "adipisci", "ut", "dolore.", "Quiquia", "numquam",
                                                "etincidunt",
                                                "tempora", "quaerat", "aliquam", "quaerat", "amet", "consectetur",
                                                "ipsum",
                                                "est", "voluptatem", "dolore", "dolore", "dolore", "modi", "velit",
                                                "tempora", "adipisci.", "Sit", "eius", "neque", "dolore", "dolor",
                                                "velit",
                                                "adipisci", "aliquam", "velit", "etincidunt", "consectetur",
                                                "voluptatem",
                                                "tempora", "dolorem", "quiquia", "dolor", "voluptatem", "etincidunt",
                                                "quisquam.", "Sit", "ipsum", "non", "quaerat", "dolore", "quiquia",
                                                "velit",
                                                "non", "est", "dolorem", "est", "adipisci", "modi", "sed", "est",
                                                "dolore",
                                                "quaerat", "non", "ut.", "Voluptatem", "etincidunt", "consectetur",
                                                "quisquam", "non", "ipsum", "eius", "adipisci", "sit", "non",
                                                "etincidunt",
                                                "adipisci", "dolore", "labore.", "Etincidunt", "ipsum", "aliquam",
                                                "sed",
                                                "ut", "quisquam", "eius", "consectetur", "velit", "porro", "numquam",
                                                "quaerat.", "Porro", "quiquia", "magnam", "amet", "eius", "quisquam",
                                                "porro", "quaerat", "quiquia", "neque", "neque", "ipsum", "neque",
                                                "amet",
                                                "labore", "dolorem.", "Numquam", "ipsum", "aliquam", "ipsum", "eius",
                                                "dolorem", "quaerat", "ut", "adipisci", "porro", "ut", "magnam", "sed",
                                                "quiquia", "est.", "Est", "aliquam", "quaerat", "eius", "magnam", "non",
                                                "modi", "quisquam", "quiquia", "dolor", "eius", "neque", "quaerat",
                                                "velit",
                                                "quaerat.", "Neque", "labore", "voluptatem", "non", "est", "porro",
                                                "labore", "porro", "numquam", "sit", "velit", "consectetur", "non",
                                                "ipsum",
                                                "magnam", "non", "labore", "labore", "porro.", "Neque", "quiquia",
                                                "velit",
                                                "eius", "eius", "ut", "labore", "etincidunt", "quiquia", "eius", "ut",
                                                "aliquam.", "Sit", "amet", "ipsum", "ipsum", "consectetur",
                                                "voluptatem",
                                                "eius", "tempora", "quiquia", "quisquam", "quaerat", "adipisci",
                                                "labore",
                                                "quisquam", "non.", "Velit", "neque", "est", "neque", "ipsum",
                                                "dolorem",
                                                "velit", "dolore", "quiquia", "velit", "magnam", "magnam", "neque",
                                                "velit",
                                                "amet", "quisquam", "quiquia", "voluptatem", "dolore", "magnam.",
                                                "Ipsum",
                                                "dolorem", "amet", "aliquam", "dolorem", "modi", "porro", "ut",
                                                "quaerat",
                                                "labore", "dolorem", "neque", "modi", "ipsum", "velit", "labore.",
                                                "Consectetur", "dolore", "aliquam", "porro", "quiquia", "amet",
                                                "etincidunt", "aliquam", "quisquam", "amet", "consectetur", "est",
                                                "labore",
                                                "dolorem.", "Ut", "labore", "neque", "ipsum", "ipsum", "amet",
                                                "quiquia",
                                                "sed", "quisquam", "velit", "sit.", "Dolor", "consectetur", "non",
                                                "adipisci", "ipsum", "dolorem", "ut", "labore", "adipisci", "quisquam.",
                                                "Sit", "tempora", "eius", "dolorem", "numquam", "consectetur", "neque",
                                                "quiquia", "eius", "sed", "amet", "neque", "adipisci", "sed", "sit",
                                                "aliquam", "quaerat", "labore.", "Ut", "quaerat", "etincidunt",
                                                "numquam",
                                                "sit", "quiquia", "consectetur", "porro", "neque", "numquam", "tempora",
                                                "magnam", "voluptatem.", "Amet", "dolore", "magnam", "adipisci",
                                                "consectetur", "non", "quaerat", "dolorem", "eius", "neque", "est",
                                                "quisquam", "neque", "amet.", "Etincidunt", "consectetur", "voluptatem",
                                                "modi", "eius", "dolorem", "quisquam", "amet", "eius", "voluptatem",
                                                "dolor", "tempora.", "Etincidunt", "sit", "est", "quiquia", "quiquia",
                                                "adipisci", "dolorem", "quiquia", "magnam", "adipisci", "magnam",
                                                "dolor",
                                                "dolor", "amet", "magnam", "modi", "non", "modi.", "Labore", "aliquam",
                                                "magnam", "tempora", "quiquia", "est", "ipsum", "quiquia", "dolor",
                                                "modi",
                                                "sit", "non", "sed", "voluptatem", "ipsum", "eius.", "Ipsum", "ut",
                                                "quisquam", "consectetur", "quiquia", "non", "porro", "numquam", "sit",
                                                "magnam", "est", "modi", "quisquam", "neque", "amet", "sed", "porro",
                                                "dolorem.", "Quisquam", "neque", "non", "voluptatem", "dolore", "velit",
                                                "numquam", "dolorem", "labore", "aliquam", "velit", "amet", "velit",
                                                "numquam", "tempora", "amet", "neque", "quaerat.", "Dolorem",
                                                "etincidunt",
                                                "porro", "aliquam", "non", "aliquam", "adipisci", "porro", "tempora",
                                                "non",
                                                "porro", "labore", "adipisci", "voluptatem", "etincidunt", "ipsum.",
                                                "Dolore", "etincidunt", "adipisci", "modi", "ut", "dolor", "sit",
                                                "neque",
                                                "eius", "dolorem", "adipisci.", "Non", "etincidunt", "sed", "ut",
                                                "ipsum",
                                                "consectetur", "dolor", "ut", "quisquam", "tempora", "quiquia",
                                                "voluptatem", "tempora.", "Amet", "tempora", "numquam", "eius",
                                                "aliquam",
                                                "sit", "quaerat", "velit", "quaerat", "velit", "aliquam", "quaerat.",
                                                "Est",
                                                "non", "quaerat", "sit", "quaerat", "labore", "aliquam", "quaerat",
                                                "modi",
                                                "ipsum", "magnam", "ut", "quisquam", "velit", "tempora.", "Eius",
                                                "consectetur", "dolore", "aliquam", "modi", "quisquam", "neque", "modi",
                                                "modi", "numquam", "quiquia", "velit.", "Sed", "non", "etincidunt",
                                                "sit",
                                                "amet", "consectetur", "tempora", "non", "ut", "est", "dolore",
                                                "dolorem",
                                                "ut.", "Quaerat", "sed", "ut", "magnam", "magnam", "dolorem", "non",
                                                "voluptatem", "sed", "magnam", "aliquam", "aliquam", "porro",
                                                "quisquam.",
                                                "Quaerat", "labore", "dolorem", "dolor", "labore", "magnam",
                                                "etincidunt",
                                                "numquam", "velit", "modi", "labore", "amet", "aliquam", "neque",
                                                "quisquam", "adipisci.", "Quaerat", "dolore", "quisquam", "amet",
                                                "dolorem",
                                                "etincidunt", "porro", "ipsum", "dolor", "quiquia", "numquam", "ut",
                                                "ipsum", "est", "quaerat", "ipsum", "ut", "consectetur.", "Dolore",
                                                "quaerat", "neque", "sed", "tempora", "neque", "dolorem", "ipsum",
                                                "modi",
                                                "dolorem", "eius", "dolore", "amet", "sed", "est", "etincidunt",
                                                "velit",
                                                "consectetur.", "Eius", "consectetur", "dolor", "etincidunt", "neque",
                                                "non", "dolore", "amet", "neque", "porro", "quaerat", "voluptatem",
                                                "est",
                                                "velit", "numquam", "ut", "velit", "neque", "labore", "neque.",
                                                "Aliquam",
                                                "ipsum", "ut", "quiquia", "dolore", "ipsum", "ipsum", "ipsum",
                                                "etincidunt",
                                                "aliquam", "consectetur", "est", "adipisci", "neque", "quisquam",
                                                "dolorem",
                                                "dolorem.", "Amet", "adipisci", "labore", "sit", "modi", "voluptatem",
                                                "eius", "velit", "velit", "eius", "dolor", "adipisci", "velit", "non",
                                                "ipsum", "voluptatem.", "Dolor", "labore", "ut", "ut", "magnam",
                                                "neque",
                                                "adipisci", "consectetur", "magnam", "aliquam", "amet", "modi",
                                                "tempora",
                                                "modi.", "Voluptatem", "est", "non", "velit", "dolore", "magnam",
                                                "eius",
                                                "neque", "neque", "non", "eius.", "Consectetur", "dolor", "est", "amet",
                                                "consectetur", "sit", "adipisci", "aliquam", "quaerat", "ut", "labore",
                                                "dolorem.", "Porro", "porro", "magnam", "quisquam", "quiquia", "ipsum",
                                                "ipsum", "ut", "consectetur", "dolor.", "Eius", "quaerat", "numquam",
                                                "sed",
                                                "sed", "dolor", "magnam", "magnam", "voluptatem", "velit", "ipsum",
                                                "est",
                                                "dolor", "dolorem", "voluptatem.", "Velit", "sit", "quaerat", "eius",
                                                "sit",
                                                "tempora", "sit", "est", "modi", "eius", "porro", "ut.", "Quiquia",
                                                "etincidunt", "sit", "ut", "etincidunt", "sit", "dolorem", "dolore",
                                                "labore", "amet", "amet", "ut", "dolorem", "quisquam", "velit",
                                                "numquam",
                                                "consectetur."};
      ngram::NGramCounter ngc_lorem4(4);
      ngc_lorem4.process(tokens_lorem4);
      ASSERT_EQ(ngc_lorem4.count_tokens(), 2597);
      ASSERT_EQ(ngc_lorem4.get(ngram::NGramContainer("consectetur.", "Eius", "consectetur", "dolor")), 1);
      ASSERT_EQ(ngc_lorem4.get(ngram::NGramContainer("neque")), 45);
      ASSERT_EQ(ngc_lorem4.get(ngram::NGramContainer("quisquam", "quiquia")), 4);
      ASSERT_EQ(ngc_lorem4.get(ngram::NGramContainer("est", "quaerat")), 3);

      ASSERT_EQ(std::distance(ngc_lorem4.begin(1), ngc_lorem4.end(1)), 76);
      ASSERT_EQ(std::distance(ngc_lorem4.begin(2), ngc_lorem4.end(2)), 651);
      ASSERT_EQ(std::distance(ngc_lorem4.begin(3), ngc_lorem4.end(3)), 930);
      ASSERT_EQ(std::distance(ngc_lorem4.begin(4), ngc_lorem4.end(4)), 940);


    }

} // namespace
