name: Deploy and execute Bitextor
on:
- push
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
         with:
            ref: actions
      -  name: Install Bitextor
         uses: ./.github/actions/installBitextor
      -  name: Run Bitextor
         run: ./bitextor.sh