name: Deploy and execute Bitextor
on:
- push
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@actions
         - name: Install Bitextor
           uses: ./.github/actions/installBitextor@actions
         - name: Run Bitextor
           run: ./bitextor.sh