name: Deferred testing

on:
   push:
      paths-ignore:
         - '**.md'
         - 'docs/**'
   pull_request:
      paths-ignore:
         - '**.md'
         - 'docs/**'

env:
   WORK: ${{ github.workspace }}

jobs:
   build_and_testing:
      name: Deferred crawling testing
      runs-on: ubuntu-22.04
      timeout-minutes: 360
      steps:
      -  name: Install required linux packages
         run: |
            sudo apt --assume-yes update
            sudo apt --assume-yes install cmake automake liblzma-dev time poppler-utils libboost-all-dev pkg-config curl git pigz wget zlib1g zlib1g-dev libgoogle-perftools-dev libunwind-dev libsparsehash-dev coreutils uchardet libuchardet-dev libzip-dev libhunspell-dev hunspell-fr autopoint
      -  name: Set up Python3
         uses: actions/setup-python@v2
         with:
            python-version: '3.10.6'
            architecture: 'x64'
      -  name: Install Python dev tools
         run: |
            sudo apt --assume-yes install python3-venv python3-setuptools
            pip3 install --upgrade pip setuptools wheel
            pip3 install Cython
      -  name: Set up JDK
         uses: actions/setup-java@v1
         with:
            java-version: 8
            java-package: jdk
            architecture: x64
      -  uses: actions/checkout@v3
         with:
            submodules: 'recursive'
      -  name: Install additional python requirements
         run: |
            pip3 install .[all]
            pip3 install git+https://github.com/MSeal/cython_hunspell@2.0.3
            pip3 install ./third_party/bifixer
            pip3 install ./third_party/bicleaner
            pip3 install ./third_party/kenlm --config-settings="--build-option=--max_order=7"
            pip3 install ./third_party/biroamer
            python3 -c "from flair.models import SequenceTagger; SequenceTagger.load('flair/ner-english-fast')"
            pip3 install -r ./third_party/deferred-crawling/requirements.txt
      -  name: Setup golang
         uses: actions/setup-go@v2
         with:
            go-version: 1.17.3
      -  name: Install giashard
         run: |
            go install github.com/paracrawl/giashard/cmd/giashard@latest
      -  name: Compiling bitextor and submodules
         run: |
            mkdir build_cmake && cd build_cmake
            cmake -DCMAKE_INSTALL_PREFIX=/usr ..
            make -j
            sudo make install
      -  name: Run tests
         run: |
            chmod 775 ./tests/run-deferred-tests.sh
            ./tests/run-deferred-tests.sh -w "$WORK" -j 4
      -  name: Upload sent.gz files (artifacts)
         if: ${{ always() }}
         uses: actions/upload-artifact@v3
         with:
            name: all-sent.gz
            path: ${{ env.WORK }}/permanent/**/*.sent.gz
      -  name: Upload report files (artifacts)
         if: ${{ always() }}
         uses: actions/upload-artifact@v3
         with:
            name: reports
            path: ${{ env.WORK }}/reports/*.report
