bitextor: /home/mespla/Projects/bitextor-malign
bitextor-installation: /home/mespla/Projects/bitextor-malign
domains: ['www.elenacaffe1863.com','vade-retro.fr']
documentAligner: DIC
#documentAligner: externalMT
temp: /tmp/transient
httrack: true
permanentDir: /tmp/persistent/bitextor-output
transientDir: /tmp/transient
nmt: false
smt: false
lang1: fr
lang2: en
nltk: true
dic: /tmp/persistent/en-fr.dic
minquality: 0
maxlines: 5
elrc: true
crawler-num-threads: 2
crawl-tld: false
bicleaner: /home/mespla/fr-en/training.en-fr.yaml
mosesDir: /home/mespla/Programari/mosesdecoder-RELEASE-4.0
tmx: true
initCorpusTrainPrefix: [/tmp/persistent/EUconst.en-fr]
bicleanerCorpusTrainingPrefix: [/tmp/persistent/RF.en-fr]
LANG1Tokenizer: /home/mespla/Projects/bitextor-malign/preprocess/moses/tokenizer/tokenizer.perl -a -b -q -l fr
LANG2Tokenizer: /home/mespla/Projects/bitextor-malign/preprocess/moses/tokenizer/tokenizer.perl -a -b -q -l en
LANG1SentenceSplitter: /home/mespla/Projects/bitextor-malign/preprocess/moses/ems/support/split-sentences.perl -l fr
LANG2SentenceSplitter: /home/mespla/Projects/bitextor-malign/preprocess/moses/ems/support/split-sentences.perl -l en
deduped: false
alignerCmd: ~/Projects/bitextor-malign/snakemake/example/translate.miquel.sh
#boilerpipeCleaning: True
#bleualign: true
