permanentDir: /home/lpla/en-mt-paracrawl
lang1: en
lang2: mt

segModel: {mt: "" , en: ""}
bpeOperations: 25000


initCorpusTrainPrefix: ["/home/lpla/marian/corpus-with-paracrawl"]
initCorpusDevPrefix:   ["/home/lpla/marian/dev"]
initCorpusTestPrefix:  ["/home/lpla/marian/test"]

toolsDir: /neural/tools4marian
marianDir: /home/lpla/marian
subwordNmtDir: /neural/tools4marian/subword-nmt
mosesDir: /neural/tools4marian/moses-scripts
smartSegmentationDir: /home/vmsanchez/smart-segmentation
temp: /home/lpla/tmp

gpuId: 0 

marianArgs: [" --sync-sgd --beam-size 12 --normalize 1",
             "--type transformer --mini-batch-fit --mini-batch 1000 --maxi-batch 1000 -w 8000 --valid-mini-batch 32",
             "--overwrite --keep-best",
             "--transformer-dropout 0.1 --label-smoothing 0.1 --optimizer-params 0.9 0.98 1e-09 --clip-norm 5",
             "--learn-rate 0.0003 --lr-warmup 16000 --lr-decay-inv-sqrt 16000 --lr-report",
             "--enc-depth 6 --dec-depth 6 --tied-embeddings-all  --exponential-smoothing",
             "--valid-metrics ce-mean-words perplexity translation --cost-type=ce-mean-words",
             "--valid-script-path \"bash /neural/tools4marian/validate.sh /neural/tools4marian/moses-scripts mt /home/lpla/marian/dev.mt\"",
             "--early-stopping 5 --valid-freq 5000 --save-freq 5000 --disp-freq 500",
             "--quiet-translation --max-length 100 --valid-max-length 100 --max-length-crop"
            ]

marianModelFile: model.npz.best-translation.npz.decoder.yml
